### ISSUE TITLE
Error with bin/solr package add-repo data-import-handler

### ISSUE THREAD

**Issue by sajiljosephs** [SearchScale/dataimporthandler#40]
**I am using 9.2.0 and this doesnt seems to work. Can you confirm if this works with 9.2.0**

Error:
bin/solr package add-repo data-import-handler "https://raw.githubusercontent.com/searchscale/dataimporthandler/master/repo/"
com.fasterxml.jackson.databind.JsonMappingException: java.net.SocketException: Network is unreachable (through reference chain: java.util.ArrayList[0]->org.apache.solr.packagemanager.DefaultPackageRepository["packages"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:361)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:782)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4624)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3869)
	at org.apache.solr.packagemanager.RepositoryManager.addRepository(RepositoryManager.java:122)
	at org.apache.solr.util.PackageTool.runImpl(PackageTool.java:97)
	at org.apache.solr.util.SolrCLI$ToolBase.runTool(SolrCLI.java:170)
	at org.apache.solr.util.SolrCLI.main(SolrCLI.java:305)
Caused by: java.lang.RuntimeException: java.net.SocketException: Network is unreachable
	at org.apache.solr.packagemanager.PackageUtils.getJsonStringFromUrl(PackageUtils.java:154)
	at org.apache.solr.packagemanager.PackageUtils.getJson(PackageUtils.java:119)
	at org.apache.solr.packagemanager.DefaultPackageRepository.initPackages(DefaultPackageRepository.java:106)
	at org.apache.solr.packagemanager.DefaultPackageRepository.getPackages(DefaultPackageRepository.java:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:689)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
	... 12 more
Caused by: java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:579)
	at java.base/sun.nio.ch.Net.connect(Net.java:568)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:639)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:368)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.apache.solr.packagemanager.PackageUtils.getJsonStringFromUrl(PackageUtils.java:146)
	... 21 more

ERROR: java.net.SocketException: Network is unreachable (through reference chain: java.util.ArrayList[0]->org.apache.solr.packagemanager.DefaultPackageRepository["packages"])

**I had cloned the project then then tried adding**

Error:
bin/solr package add-repo data-import-handler repo/
com.fasterxml.jackson.databind.JsonMappingException: org.apache.http.client.ClientProtocolException (through reference chain: java.util.ArrayList[0]->org.apache.solr.packagemanager.DefaultPackageRepository["packages"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:361)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:782)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4624)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3869)
	at org.apache.solr.packagemanager.RepositoryManager.addRepository(RepositoryManager.java:122)
	at org.apache.solr.util.PackageTool.runImpl(PackageTool.java:97)
	at org.apache.solr.util.SolrCLI$ToolBase.runTool(SolrCLI.java:170)
	at org.apache.solr.util.SolrCLI.main(SolrCLI.java:305)
Caused by: java.lang.RuntimeException: org.apache.http.client.ClientProtocolException
	at org.apache.solr.packagemanager.PackageUtils.getJsonStringFromUrl(PackageUtils.java:154)
	at org.apache.solr.packagemanager.PackageUtils.getJson(PackageUtils.java:119)
	at org.apache.solr.packagemanager.DefaultPackageRepository.initPackages(DefaultPackageRepository.java:106)
	at org.apache.solr.packagemanager.DefaultPackageRepository.getPackages(DefaultPackageRepository.java:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:689)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
	... 12 more
Caused by: org.apache.http.client.ClientProtocolException
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:187)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.apache.solr.packagemanager.PackageUtils.getJsonStringFromUrl(PackageUtils.java:146)
	... 21 more
Caused by: org.apache.http.ProtocolException: Target host is not specified
	at org.apache.http.impl.conn.DefaultRoutePlanner.determineRoute(DefaultRoutePlanner.java:71)
	at org.apache.http.impl.client.InternalHttpClient.determineRoute(InternalHttpClient.java:125)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	... 25 more

ERROR: org.apache.http.client.ClientProtocolException (through reference chain: java.util.ArrayList[0]->org.apache.solr.packagemanager.DefaultPackageRepository["packages"])

Can you suggest what needs to be modified ?

**Comment by sajiljosephs** [comment]
I could see the same error while trying with 9.0.0 also
