### ISSUE TITLE
DIH with Solr 9.3.0

### ISSUE THREAD

**Issue by zniff** [SearchScale/dataimporthandler#47]
Hi everybody

I just tried to run data-import-handler-9.2.1.jar with Solr 9.3.0 but it looks like some previously deprecated methods and constructors were removed in this version and therefore "java.lang.NoSuchMethodError" exceptions are thrown:

Constructor `MetricsMap​(BiConsumer<Boolean,​Map<String,​Object>> mapInitializer)` was removed.

```
Caused by: java.lang.NoSuchMethodError: 'void org.apache.solr.metrics.MetricsMap.<init>(java.util.function.BiConsumer)'
	at org.apache.solr.handler.dataimport.DataImportHandler.initializeMetrics(DataImportHandler.java:285)
	at org.apache.solr.metrics.SolrCoreMetricManager.registerMetricProducer(SolrCoreMetricManager.java:139)
	at org.apache.solr.core.SolrCore.registerInfoBean(SolrCore.java:3458)
	at org.apache.solr.core.PluginBag.registerMBean(PluginBag.java:366)
	at org.apache.solr.core.PluginBag.put(PluginBag.java:283)
	at org.apache.solr.core.PluginBag.init(PluginBag.java:332)
	at org.apache.solr.core.RequestHandlers.initHandlersFromConfig(RequestHandlers.java:119)
	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:1142)

```

see https://solr.apache.org/docs/9_3_0/changes/Changes.html#v9.3.0.other_changes and https://github.com/apache/solr/pull/1567 and https://solr.apache.org/docs/9_3_0/core/org/apache/solr/metrics/MetricsMap.html

best regards
Erich

**Comment by aadrian** [comment]
@zniff  https://github.com/SearchScale/dataimporthandler/pull/48

Unfortunately more was removed than in MetricsMap, thus making some tests fragile ( see HttpSolrClient timout settings ).

**Comment by zniff** [comment]
Just tested with the latest 9.3.0 dataimport handler and everything works fine so far.
Thanks a lot!
